### ISSUE TITLE
代码实现

### ISSUE THREAD

**Issue by 2504320240** [NJU-LHRS/official-CMID#29]
你好，我在实现你的基于Swin-b的场景分类任务时，在cla_model.py中的第161行x, target = x
代码报错ValueError: not enough values to unpack (expected 2, got 1)
请看看代码实现是否有误？

**Comment by lmbrohw** [comment]
您好，请问解决了吗

**Comment by 2504320240** [comment]
> 您好，请问解决了吗

没有

**Comment by pUmpKin-Co** [comment]
您好。

启动程序的命令可以提供一下嘛，我这样看了一下没看出什么问题。

**Comment by lmbrohw** [comment]
您好，跑微调分类图片的任务：
`python main_finetune.py -c ~/autodl-tmp/cmid/Pretrain/ft_config.yaml \
      --batch-size 16 \
      --data-path ~/autodl-tmp/cmid/UCM  \
      --workers 8 \
      --accelerator gpu \
      --output ~/autodl-tmp/cmid/Result \
      --enable_amp True \
      --infloader True \
      --checkpoint_path ~/autodl-tmp/cmid/Checkpoint/CMID_Swin-B_bk_200ep`
      
      报错
`[11/20 13:19:11 train]: Start training from epoch 0
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_normalization() for <class 'torch.nn.modules.normalization.LayerNorm'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.dropout.Dropout'>.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[INFO] Register count_softmax() for <class 'torch.nn.modules.activation.Softmax'>.
[INFO] Register count_adap_avgpool() for <class 'torch.nn.modules.pooling.AdaptiveAvgPool2d'>.
Traceback (most recent call last):
  File "/root/autodl-tmp/cmid/Pretrain/main_finetune.py", line 157, in <module>
    main(config)
  File "/root/autodl-tmp/cmid/Pretrain/main_finetune.py", line 118, in main
    trainer.train(load_checkpoint=config.resume_path)
  File "/root/autodl-tmp/cmid/Pretrain/Exploring/trainer.py", line 404, in train
    self._call_hooks("before_train")
  File "/root/autodl-tmp/cmid/Pretrain/Exploring/trainer.py", line 307, in _call_hooks
    getattr(h, stage)()
  File "/root/autodl-tmp/cmid/Pretrain/Exploring/hook/param_flops_hook.py", line 19, in before_train
    flops, params = profile(self.trainer.model, inputs=dict(x=sample_data, return_loss=False, eval=True, device=self.trainer.device))
  File "/root/miniconda3/envs/tf/lib/python3.9/site-packages/thop/profile.py", line 212, in profile
    model(*inputs)
  File "/root/miniconda3/envs/tf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/cmid/Pretrain/models/clas_model.py", line 162, in forward
    x, target = x
ValueError: not enough values to unpack (expected 2, got 1)`

感谢感谢

**Comment by 2504320240** [comment]
我设置也是同上
感谢

**Comment by pUmpKin-Co** [comment]
注释掉[这一行](https://github.com/NJU-LHRS/official-CMID/blob/c217ccde74f00e7ac8dcd6ea85964a6fc93e0de1/Pretrain/main_finetune.py#L115)和下面的一行(Line 115, 116)试一下，
计算Flops的时候没有输入target，所以报的错应该.

**Comment by lmbrohw** [comment]
哇，感谢。已经改好了。

**Comment by 2504320240** [comment]
哇 感谢大佬 我也改好了

**Comment by 2504320240** [comment]
大佬您好 我还想问一下分类任务中您的代码经过finetune后进行分类OA指标的是哪个脚本？
感谢

**Comment by 2504320240** [comment]
您好，我想问一下分类任务中finetune过后进行OA输出的脚本是哪个？
感谢

**Comment by lmbrohw** [comment]
我把代码中
    hooks = [EvalHook(period=1), CounterHook()]
    trainer.register_hook(hooks)
    不注释，改为
    hooks = [EvalHook(period=1)]
    trainer.register_hook(hooks)
    能看到分类的 oa结果，但是非常低。请问您这边的 oa结果怎么样呢

**Comment by 2504320240** [comment]
我按照您说的改了一下 OA结果也是很低

**Comment by 2504320240** [comment]
> 我把代码中 hooks = [EvalHook(period=1), CounterHook()] trainer.register_hook(hooks) 不注释，改为 hooks = [EvalHook(period=1)] trainer.register_hook(hooks) 能看到分类的 oa结果，但是非常低。请问您这边的 oa结果怎么样呢

您好，我使用resnet50然后下载Scene Classification (UCM 8:2)的weights，然后在finetune进行您后面修改的那个代码，然后在第一个epoch的acc到达了99%
![1](https://github.com/user-attachments/assets/388b0bad-e6e6-4923-ad70-295cdd3f396d)

**Comment by kakaduse** [comment]
请问你这里用作者提供的微调好的模型进行测试是用什么指令来进行的，或者在运行main_finetune.py之前需要进行什么处理吗，我用指令来跑会报错说是模型不匹配。
